modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="MIT License"

[[mods]] #mandatory
modId="throwablebricks" #mandatory
version="1.0.0" #mandatory
logoFile="logo.png" #optional
displayName="Simple Throwable Bricks" #mandatory
credits="Thanks to TurtyWurty and YodaForce157 for helping me out in TurtyWurty's discord server."
authors="Miki1106" #optional
description='''Makes Bricks throwable.
Because why not?'''
[[dependencies.throwablebricks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.throwablebricks]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"