modLoader="javafml" #mandatory
loaderVersion="[0,)"
license="MIT License"

[[mods]] #mandatory
modId="throwablebricks" #mandatory
version="1.0" #mandatory
logoFile="logo.png" #optional
displayName="Simple Throwable Bricks" #mandatory
authors="Miki1106" #optional
description='''Makes Bricks throwable.
Because why not?'''
[[dependencies.throwablebricks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.throwablebricks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4,)"
    ordering="NONE"
    side="BOTH"